<?php declare(strict_types=1);

namespace Ardenexal\FHIRTools\Component\Models\R4B\DataType;

/**
 * @author HL7 FHIR Standard
 * @see http://hl7.org/fhir/StructureDefinition/Extension
 * @description Optional Extension Element - found in all resources.
 */
#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FHIRComplexType(typeName: 'Extension', fhirVersion: 'R4B')]
class Extension extends Element
{
	public const FHIR_PROPERTY_MAP = [
		'id' => [
			'fhirType' => 'http://hl7.org/fhirpath/System.String',
			'propertyKind' => 'scalar',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'extension' => [
			'fhirType' => 'Extension',
			'propertyKind' => 'extension',
			'isArray' => true,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'url' => [
			'fhirType' => 'http://hl7.org/fhirpath/System.String',
			'propertyKind' => 'scalar',
			'isArray' => false,
			'isRequired' => true,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'valueX' => [
			'fhirType' => 'choice',
			'propertyKind' => 'choice',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => true,
			'jsonKey' => null,
			'variants' => [
				[
					'fhirType' => 'base64Binary',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\Base64BinaryPrimitive',
					'jsonKey' => 'valueBase64Binary',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'boolean',
					'propertyKind' => 'scalar',
					'phpType' => 'bool',
					'jsonKey' => 'valueBoolean',
					'isBuiltin' => true,
				],
				[
					'fhirType' => 'canonical',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CanonicalPrimitive',
					'jsonKey' => 'valueCanonical',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'code',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CodePrimitive',
					'jsonKey' => 'valueCode',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'date',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DatePrimitive',
					'jsonKey' => 'valueDate',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'dateTime',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DateTimePrimitive',
					'jsonKey' => 'valueDateTime',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'decimal',
					'propertyKind' => 'scalar',
					'phpType' => 'float',
					'jsonKey' => 'valueDecimal',
					'isBuiltin' => true,
				],
				[
					'fhirType' => 'id',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\IdPrimitive',
					'jsonKey' => 'valueId',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'instant',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\InstantPrimitive',
					'jsonKey' => 'valueInstant',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'integer',
					'propertyKind' => 'scalar',
					'phpType' => 'int',
					'jsonKey' => 'valueInteger',
					'isBuiltin' => true,
				],
				[
					'fhirType' => 'markdown',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\MarkdownPrimitive',
					'jsonKey' => 'valueMarkdown',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'oid',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\OidPrimitive',
					'jsonKey' => 'valueOid',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'positiveInt',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\PositiveIntPrimitive',
					'jsonKey' => 'valuePositiveInt',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'string',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive',
					'jsonKey' => 'valueString',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'time',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\TimePrimitive',
					'jsonKey' => 'valueTime',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'unsignedInt',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UnsignedIntPrimitive',
					'jsonKey' => 'valueUnsignedInt',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'uri',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UriPrimitive',
					'jsonKey' => 'valueUri',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'url',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UrlPrimitive',
					'jsonKey' => 'valueUrl',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'uuid',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UuidPrimitive',
					'jsonKey' => 'valueUuid',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Address',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Address',
					'jsonKey' => 'valueAddress',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Age',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Age',
					'jsonKey' => 'valueAge',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Annotation',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Annotation',
					'jsonKey' => 'valueAnnotation',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Attachment',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Attachment',
					'jsonKey' => 'valueAttachment',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'CodeableConcept',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\CodeableConcept',
					'jsonKey' => 'valueCodeableConcept',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'CodeableReference',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\CodeableReference',
					'jsonKey' => 'valueCodeableReference',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Coding',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Coding',
					'jsonKey' => 'valueCoding',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'ContactPoint',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactPoint',
					'jsonKey' => 'valueContactPoint',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Count',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Count',
					'jsonKey' => 'valueCount',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Distance',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Distance',
					'jsonKey' => 'valueDistance',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Duration',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Duration',
					'jsonKey' => 'valueDuration',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'HumanName',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\HumanName',
					'jsonKey' => 'valueHumanName',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Identifier',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Identifier',
					'jsonKey' => 'valueIdentifier',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Money',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Money',
					'jsonKey' => 'valueMoney',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Period',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Period',
					'jsonKey' => 'valuePeriod',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Quantity',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Quantity',
					'jsonKey' => 'valueQuantity',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Range',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Range',
					'jsonKey' => 'valueRange',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Ratio',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Ratio',
					'jsonKey' => 'valueRatio',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'RatioRange',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\RatioRange',
					'jsonKey' => 'valueRatioRange',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Reference',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Reference',
					'jsonKey' => 'valueReference',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'SampledData',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\SampledData',
					'jsonKey' => 'valueSampledData',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Signature',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Signature',
					'jsonKey' => 'valueSignature',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Timing',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Timing',
					'jsonKey' => 'valueTiming',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'ContactDetail',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactDetail',
					'jsonKey' => 'valueContactDetail',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Contributor',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Contributor',
					'jsonKey' => 'valueContributor',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'DataRequirement',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\DataRequirement',
					'jsonKey' => 'valueDataRequirement',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Expression',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Expression',
					'jsonKey' => 'valueExpression',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'ParameterDefinition',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\ParameterDefinition',
					'jsonKey' => 'valueParameterDefinition',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'RelatedArtifact',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\RelatedArtifact',
					'jsonKey' => 'valueRelatedArtifact',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'TriggerDefinition',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\TriggerDefinition',
					'jsonKey' => 'valueTriggerDefinition',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'UsageContext',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\UsageContext',
					'jsonKey' => 'valueUsageContext',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Dosage',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Dosage',
					'jsonKey' => 'valueDosage',
					'isBuiltin' => false,
				],
			],
		],
	];

	public function __construct(
		/** @var null|string id Unique id for inter-element referencing */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'http://hl7.org/fhirpath/System.String', propertyKind: 'scalar')]
		public ?string $id = null,
		/** @var  array<\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Extension> extension Additional content defined by implementations */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'Extension', propertyKind: 'extension', isArray: true)]
		public array $extension = [],
		/** @var null|string url identifies the meaning of the extension */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'http://hl7.org/fhirpath/System.String', propertyKind: 'scalar', isRequired: true), \Symfony\Component\Validator\Constraints\NotBlank]
		public ?string $url = null,
		/** @var null|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\Base64BinaryPrimitive|bool|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CanonicalPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CodePrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DatePrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DateTimePrimitive|float|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\IdPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\InstantPrimitive|int|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\MarkdownPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\OidPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\PositiveIntPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\TimePrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UnsignedIntPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UriPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UrlPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UuidPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Address|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Age|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Annotation|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Attachment|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\CodeableConcept|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\CodeableReference|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Coding|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactPoint|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Count|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Distance|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Duration|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\HumanName|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Identifier|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Money|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Period|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Quantity|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Range|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Ratio|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\RatioRange|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Reference|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\SampledData|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Signature|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Timing|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactDetail|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Contributor|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\DataRequirement|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Expression|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\ParameterDefinition|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\RelatedArtifact|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\TriggerDefinition|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\UsageContext|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Dosage valueX Value of extension */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(
			fhirType: 'choice',
			propertyKind: 'choice',
			isChoice: true,
			variants: [
			[
				'fhirType' => 'base64Binary',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\Base64BinaryPrimitive',
				'jsonKey' => 'valueBase64Binary',
			],
			['fhirType' => 'boolean', 'propertyKind' => 'scalar', 'phpType' => 'bool', 'jsonKey' => 'valueBoolean'],
			[
				'fhirType' => 'canonical',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CanonicalPrimitive',
				'jsonKey' => 'valueCanonical',
			],
			[
				'fhirType' => 'code',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CodePrimitive',
				'jsonKey' => 'valueCode',
			],
			[
				'fhirType' => 'date',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DatePrimitive',
				'jsonKey' => 'valueDate',
			],
			[
				'fhirType' => 'dateTime',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DateTimePrimitive',
				'jsonKey' => 'valueDateTime',
			],
			['fhirType' => 'decimal', 'propertyKind' => 'scalar', 'phpType' => 'float', 'jsonKey' => 'valueDecimal'],
			[
				'fhirType' => 'id',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\IdPrimitive',
				'jsonKey' => 'valueId',
			],
			[
				'fhirType' => 'instant',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\InstantPrimitive',
				'jsonKey' => 'valueInstant',
			],
			['fhirType' => 'integer', 'propertyKind' => 'scalar', 'phpType' => 'int', 'jsonKey' => 'valueInteger'],
			[
				'fhirType' => 'markdown',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\MarkdownPrimitive',
				'jsonKey' => 'valueMarkdown',
			],
			[
				'fhirType' => 'oid',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\OidPrimitive',
				'jsonKey' => 'valueOid',
			],
			[
				'fhirType' => 'positiveInt',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\PositiveIntPrimitive',
				'jsonKey' => 'valuePositiveInt',
			],
			[
				'fhirType' => 'string',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive',
				'jsonKey' => 'valueString',
			],
			[
				'fhirType' => 'time',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\TimePrimitive',
				'jsonKey' => 'valueTime',
			],
			[
				'fhirType' => 'unsignedInt',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UnsignedIntPrimitive',
				'jsonKey' => 'valueUnsignedInt',
			],
			[
				'fhirType' => 'uri',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UriPrimitive',
				'jsonKey' => 'valueUri',
			],
			[
				'fhirType' => 'url',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UrlPrimitive',
				'jsonKey' => 'valueUrl',
			],
			[
				'fhirType' => 'uuid',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UuidPrimitive',
				'jsonKey' => 'valueUuid',
			],
			[
				'fhirType' => 'Address',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Address',
				'jsonKey' => 'valueAddress',
			],
			[
				'fhirType' => 'Age',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Age',
				'jsonKey' => 'valueAge',
			],
			[
				'fhirType' => 'Annotation',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Annotation',
				'jsonKey' => 'valueAnnotation',
			],
			[
				'fhirType' => 'Attachment',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Attachment',
				'jsonKey' => 'valueAttachment',
			],
			[
				'fhirType' => 'CodeableConcept',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\CodeableConcept',
				'jsonKey' => 'valueCodeableConcept',
			],
			[
				'fhirType' => 'CodeableReference',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\CodeableReference',
				'jsonKey' => 'valueCodeableReference',
			],
			[
				'fhirType' => 'Coding',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Coding',
				'jsonKey' => 'valueCoding',
			],
			[
				'fhirType' => 'ContactPoint',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactPoint',
				'jsonKey' => 'valueContactPoint',
			],
			[
				'fhirType' => 'Count',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Count',
				'jsonKey' => 'valueCount',
			],
			[
				'fhirType' => 'Distance',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Distance',
				'jsonKey' => 'valueDistance',
			],
			[
				'fhirType' => 'Duration',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Duration',
				'jsonKey' => 'valueDuration',
			],
			[
				'fhirType' => 'HumanName',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\HumanName',
				'jsonKey' => 'valueHumanName',
			],
			[
				'fhirType' => 'Identifier',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Identifier',
				'jsonKey' => 'valueIdentifier',
			],
			[
				'fhirType' => 'Money',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Money',
				'jsonKey' => 'valueMoney',
			],
			[
				'fhirType' => 'Period',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Period',
				'jsonKey' => 'valuePeriod',
			],
			[
				'fhirType' => 'Quantity',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Quantity',
				'jsonKey' => 'valueQuantity',
			],
			[
				'fhirType' => 'Range',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Range',
				'jsonKey' => 'valueRange',
			],
			[
				'fhirType' => 'Ratio',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Ratio',
				'jsonKey' => 'valueRatio',
			],
			[
				'fhirType' => 'RatioRange',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\RatioRange',
				'jsonKey' => 'valueRatioRange',
			],
			[
				'fhirType' => 'Reference',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Reference',
				'jsonKey' => 'valueReference',
			],
			[
				'fhirType' => 'SampledData',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\SampledData',
				'jsonKey' => 'valueSampledData',
			],
			[
				'fhirType' => 'Signature',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Signature',
				'jsonKey' => 'valueSignature',
			],
			[
				'fhirType' => 'Timing',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Timing',
				'jsonKey' => 'valueTiming',
			],
			[
				'fhirType' => 'ContactDetail',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactDetail',
				'jsonKey' => 'valueContactDetail',
			],
			[
				'fhirType' => 'Contributor',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Contributor',
				'jsonKey' => 'valueContributor',
			],
			[
				'fhirType' => 'DataRequirement',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\DataRequirement',
				'jsonKey' => 'valueDataRequirement',
			],
			[
				'fhirType' => 'Expression',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Expression',
				'jsonKey' => 'valueExpression',
			],
			[
				'fhirType' => 'ParameterDefinition',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\ParameterDefinition',
				'jsonKey' => 'valueParameterDefinition',
			],
			[
				'fhirType' => 'RelatedArtifact',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\RelatedArtifact',
				'jsonKey' => 'valueRelatedArtifact',
			],
			[
				'fhirType' => 'TriggerDefinition',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\TriggerDefinition',
				'jsonKey' => 'valueTriggerDefinition',
			],
			[
				'fhirType' => 'UsageContext',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\UsageContext',
				'jsonKey' => 'valueUsageContext',
			],
			[
				'fhirType' => 'Dosage',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Dosage',
				'jsonKey' => 'valueDosage',
			],
		],
		)]
		public \Ardenexal\FHIRTools\Component\Models\R4B\Primitive\Base64BinaryPrimitive|bool|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CanonicalPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CodePrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DatePrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DateTimePrimitive|float|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\IdPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\InstantPrimitive|int|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\MarkdownPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\OidPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\PositiveIntPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\TimePrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UnsignedIntPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UriPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UrlPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UuidPrimitive|Address|Age|Annotation|Attachment|CodeableConcept|CodeableReference|Coding|ContactPoint|Count|Distance|Duration|HumanName|Identifier|Money|Period|Quantity|Range|Ratio|RatioRange|Reference|SampledData|Signature|Timing|ContactDetail|Contributor|DataRequirement|Expression|ParameterDefinition|RelatedArtifact|TriggerDefinition|UsageContext|Dosage|null $valueX = null,
	) {
		parent::__construct($id, $extension);
	}
}
