<?php declare(strict_types=1);

namespace Ardenexal\FHIRTools\Component\Models\R5\Resource\Transport;

/**
 * @description Outputs produced by the Transport.
 */
#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FHIRBackboneElement(parentResource: 'Transport', elementPath: 'Transport.output', fhirVersion: 'R5')]
class TransportOutput extends \Ardenexal\FHIRTools\Component\Models\R5\DataType\BackboneElement
{
	public const FHIR_PROPERTY_MAP = [
		'id' => [
			'fhirType' => 'http://hl7.org/fhirpath/System.String',
			'propertyKind' => 'scalar',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'extension' => [
			'fhirType' => 'Extension',
			'propertyKind' => 'extension',
			'isArray' => true,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'modifierExtension' => [
			'fhirType' => 'Extension',
			'propertyKind' => 'modifierExtension',
			'isArray' => true,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'type' => [
			'fhirType' => 'CodeableConcept',
			'propertyKind' => 'complex',
			'isArray' => false,
			'isRequired' => true,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'value' => [
			'fhirType' => 'choice',
			'propertyKind' => 'choice',
			'isArray' => false,
			'isRequired' => true,
			'isChoice' => true,
			'jsonKey' => null,
			'variants' => [
				[
					'fhirType' => 'base64Binary',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\Base64BinaryPrimitive',
					'jsonKey' => 'valueBase64Binary',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'boolean',
					'propertyKind' => 'scalar',
					'phpType' => 'bool',
					'jsonKey' => 'valueBoolean',
					'isBuiltin' => true,
				],
				[
					'fhirType' => 'canonical',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\CanonicalPrimitive',
					'jsonKey' => 'valueCanonical',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'code',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\CodePrimitive',
					'jsonKey' => 'valueCode',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'date',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\DatePrimitive',
					'jsonKey' => 'valueDate',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'dateTime',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\DateTimePrimitive',
					'jsonKey' => 'valueDateTime',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'decimal',
					'propertyKind' => 'scalar',
					'phpType' => 'float',
					'jsonKey' => 'valueDecimal',
					'isBuiltin' => true,
				],
				[
					'fhirType' => 'id',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\IdPrimitive',
					'jsonKey' => 'valueId',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'instant',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\InstantPrimitive',
					'jsonKey' => 'valueInstant',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'integer',
					'propertyKind' => 'scalar',
					'phpType' => 'int',
					'jsonKey' => 'valueInteger',
					'isBuiltin' => true,
				],
				[
					'fhirType' => 'integer64',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\Integer64Primitive',
					'jsonKey' => 'valueInteger64',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'markdown',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\MarkdownPrimitive',
					'jsonKey' => 'valueMarkdown',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'oid',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\OidPrimitive',
					'jsonKey' => 'valueOid',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'positiveInt',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\PositiveIntPrimitive',
					'jsonKey' => 'valuePositiveInt',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'string',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\StringPrimitive',
					'jsonKey' => 'valueString',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'time',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\TimePrimitive',
					'jsonKey' => 'valueTime',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'unsignedInt',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\UnsignedIntPrimitive',
					'jsonKey' => 'valueUnsignedInt',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'uri',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\UriPrimitive',
					'jsonKey' => 'valueUri',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'url',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\UrlPrimitive',
					'jsonKey' => 'valueUrl',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'uuid',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\UuidPrimitive',
					'jsonKey' => 'valueUuid',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Address',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Address',
					'jsonKey' => 'valueAddress',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Age',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Age',
					'jsonKey' => 'valueAge',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Annotation',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Annotation',
					'jsonKey' => 'valueAnnotation',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Attachment',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Attachment',
					'jsonKey' => 'valueAttachment',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'CodeableConcept',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\CodeableConcept',
					'jsonKey' => 'valueCodeableConcept',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'CodeableReference',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\CodeableReference',
					'jsonKey' => 'valueCodeableReference',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Coding',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Coding',
					'jsonKey' => 'valueCoding',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'ContactPoint',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\ContactPoint',
					'jsonKey' => 'valueContactPoint',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Count',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Count',
					'jsonKey' => 'valueCount',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Distance',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Distance',
					'jsonKey' => 'valueDistance',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Duration',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Duration',
					'jsonKey' => 'valueDuration',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'HumanName',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\HumanName',
					'jsonKey' => 'valueHumanName',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Identifier',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Identifier',
					'jsonKey' => 'valueIdentifier',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Money',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Money',
					'jsonKey' => 'valueMoney',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Period',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Period',
					'jsonKey' => 'valuePeriod',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Quantity',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Quantity',
					'jsonKey' => 'valueQuantity',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Range',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Range',
					'jsonKey' => 'valueRange',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Ratio',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Ratio',
					'jsonKey' => 'valueRatio',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'RatioRange',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\RatioRange',
					'jsonKey' => 'valueRatioRange',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Reference',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Reference',
					'jsonKey' => 'valueReference',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'SampledData',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\SampledData',
					'jsonKey' => 'valueSampledData',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Signature',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Signature',
					'jsonKey' => 'valueSignature',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Timing',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Timing',
					'jsonKey' => 'valueTiming',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'ContactDetail',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\ContactDetail',
					'jsonKey' => 'valueContactDetail',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'DataRequirement',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\DataRequirement',
					'jsonKey' => 'valueDataRequirement',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Expression',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Expression',
					'jsonKey' => 'valueExpression',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'ParameterDefinition',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\ParameterDefinition',
					'jsonKey' => 'valueParameterDefinition',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'RelatedArtifact',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\RelatedArtifact',
					'jsonKey' => 'valueRelatedArtifact',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'TriggerDefinition',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\TriggerDefinition',
					'jsonKey' => 'valueTriggerDefinition',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'UsageContext',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\UsageContext',
					'jsonKey' => 'valueUsageContext',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Availability',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Availability',
					'jsonKey' => 'valueAvailability',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'ExtendedContactDetail',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\ExtendedContactDetail',
					'jsonKey' => 'valueExtendedContactDetail',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Dosage',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Dosage',
					'jsonKey' => 'valueDosage',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Meta',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Meta',
					'jsonKey' => 'valueMeta',
					'isBuiltin' => false,
				],
			],
		],
	];

	public function __construct(
		/** @var null|string id Unique id for inter-element referencing */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'http://hl7.org/fhirpath/System.String', propertyKind: 'scalar')]
		public ?string $id = null,
		/** @var  array<\Ardenexal\FHIRTools\Component\Models\R5\DataType\Extension> extension Additional content defined by implementations */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'Extension', propertyKind: 'extension', isArray: true)]
		public array $extension = [],
		/** @var  array<\Ardenexal\FHIRTools\Component\Models\R5\DataType\Extension> modifierExtension Extensions that cannot be ignored even if unrecognized */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'Extension', propertyKind: 'modifierExtension', isArray: true)]
		public array $modifierExtension = [],
		/** @var null|\Ardenexal\FHIRTools\Component\Models\R5\DataType\CodeableConcept type Label for output */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'CodeableConcept', propertyKind: 'complex', isRequired: true), \Symfony\Component\Validator\Constraints\NotBlank]
		public ?\Ardenexal\FHIRTools\Component\Models\R5\DataType\CodeableConcept $type = null,
		/** @var null|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\Base64BinaryPrimitive|bool|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\CanonicalPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\CodePrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\DatePrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\DateTimePrimitive|float|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\IdPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\InstantPrimitive|int|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\Integer64Primitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\MarkdownPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\OidPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\PositiveIntPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\StringPrimitive|string|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\TimePrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\UnsignedIntPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\UriPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\UrlPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\UuidPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Address|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Age|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Annotation|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Attachment|\Ardenexal\FHIRTools\Component\Models\R5\DataType\CodeableConcept|\Ardenexal\FHIRTools\Component\Models\R5\DataType\CodeableReference|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Coding|\Ardenexal\FHIRTools\Component\Models\R5\DataType\ContactPoint|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Count|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Distance|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Duration|\Ardenexal\FHIRTools\Component\Models\R5\DataType\HumanName|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Identifier|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Money|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Period|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Quantity|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Range|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Ratio|\Ardenexal\FHIRTools\Component\Models\R5\DataType\RatioRange|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Reference|\Ardenexal\FHIRTools\Component\Models\R5\DataType\SampledData|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Signature|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Timing|\Ardenexal\FHIRTools\Component\Models\R5\DataType\ContactDetail|\Ardenexal\FHIRTools\Component\Models\R5\DataType\DataRequirement|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Expression|\Ardenexal\FHIRTools\Component\Models\R5\DataType\ParameterDefinition|\Ardenexal\FHIRTools\Component\Models\R5\DataType\RelatedArtifact|\Ardenexal\FHIRTools\Component\Models\R5\DataType\TriggerDefinition|\Ardenexal\FHIRTools\Component\Models\R5\DataType\UsageContext|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Availability|\Ardenexal\FHIRTools\Component\Models\R5\DataType\ExtendedContactDetail|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Dosage|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Meta value Result of output */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(
			fhirType: 'choice',
			propertyKind: 'choice',
			isRequired: true,
			isChoice: true,
			variants: [
			[
				'fhirType' => 'base64Binary',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\Base64BinaryPrimitive',
				'jsonKey' => 'valueBase64Binary',
			],
			['fhirType' => 'boolean', 'propertyKind' => 'scalar', 'phpType' => 'bool', 'jsonKey' => 'valueBoolean'],
			[
				'fhirType' => 'canonical',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\CanonicalPrimitive',
				'jsonKey' => 'valueCanonical',
			],
			[
				'fhirType' => 'code',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\CodePrimitive',
				'jsonKey' => 'valueCode',
			],
			[
				'fhirType' => 'date',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\DatePrimitive',
				'jsonKey' => 'valueDate',
			],
			[
				'fhirType' => 'dateTime',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\DateTimePrimitive',
				'jsonKey' => 'valueDateTime',
			],
			['fhirType' => 'decimal', 'propertyKind' => 'scalar', 'phpType' => 'float', 'jsonKey' => 'valueDecimal'],
			[
				'fhirType' => 'id',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\IdPrimitive',
				'jsonKey' => 'valueId',
			],
			[
				'fhirType' => 'instant',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\InstantPrimitive',
				'jsonKey' => 'valueInstant',
			],
			['fhirType' => 'integer', 'propertyKind' => 'scalar', 'phpType' => 'int', 'jsonKey' => 'valueInteger'],
			[
				'fhirType' => 'integer64',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\Integer64Primitive',
				'jsonKey' => 'valueInteger64',
			],
			[
				'fhirType' => 'markdown',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\MarkdownPrimitive',
				'jsonKey' => 'valueMarkdown',
			],
			[
				'fhirType' => 'oid',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\OidPrimitive',
				'jsonKey' => 'valueOid',
			],
			[
				'fhirType' => 'positiveInt',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\PositiveIntPrimitive',
				'jsonKey' => 'valuePositiveInt',
			],
			[
				'fhirType' => 'string',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\StringPrimitive',
				'jsonKey' => 'valueString',
			],
			[
				'fhirType' => 'time',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\TimePrimitive',
				'jsonKey' => 'valueTime',
			],
			[
				'fhirType' => 'unsignedInt',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\UnsignedIntPrimitive',
				'jsonKey' => 'valueUnsignedInt',
			],
			[
				'fhirType' => 'uri',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\UriPrimitive',
				'jsonKey' => 'valueUri',
			],
			[
				'fhirType' => 'url',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\UrlPrimitive',
				'jsonKey' => 'valueUrl',
			],
			[
				'fhirType' => 'uuid',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\Primitive\UuidPrimitive',
				'jsonKey' => 'valueUuid',
			],
			[
				'fhirType' => 'Address',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Address',
				'jsonKey' => 'valueAddress',
			],
			[
				'fhirType' => 'Age',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Age',
				'jsonKey' => 'valueAge',
			],
			[
				'fhirType' => 'Annotation',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Annotation',
				'jsonKey' => 'valueAnnotation',
			],
			[
				'fhirType' => 'Attachment',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Attachment',
				'jsonKey' => 'valueAttachment',
			],
			[
				'fhirType' => 'CodeableConcept',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\CodeableConcept',
				'jsonKey' => 'valueCodeableConcept',
			],
			[
				'fhirType' => 'CodeableReference',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\CodeableReference',
				'jsonKey' => 'valueCodeableReference',
			],
			[
				'fhirType' => 'Coding',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Coding',
				'jsonKey' => 'valueCoding',
			],
			[
				'fhirType' => 'ContactPoint',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\ContactPoint',
				'jsonKey' => 'valueContactPoint',
			],
			[
				'fhirType' => 'Count',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Count',
				'jsonKey' => 'valueCount',
			],
			[
				'fhirType' => 'Distance',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Distance',
				'jsonKey' => 'valueDistance',
			],
			[
				'fhirType' => 'Duration',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Duration',
				'jsonKey' => 'valueDuration',
			],
			[
				'fhirType' => 'HumanName',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\HumanName',
				'jsonKey' => 'valueHumanName',
			],
			[
				'fhirType' => 'Identifier',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Identifier',
				'jsonKey' => 'valueIdentifier',
			],
			[
				'fhirType' => 'Money',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Money',
				'jsonKey' => 'valueMoney',
			],
			[
				'fhirType' => 'Period',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Period',
				'jsonKey' => 'valuePeriod',
			],
			[
				'fhirType' => 'Quantity',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Quantity',
				'jsonKey' => 'valueQuantity',
			],
			[
				'fhirType' => 'Range',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Range',
				'jsonKey' => 'valueRange',
			],
			[
				'fhirType' => 'Ratio',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Ratio',
				'jsonKey' => 'valueRatio',
			],
			[
				'fhirType' => 'RatioRange',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\RatioRange',
				'jsonKey' => 'valueRatioRange',
			],
			[
				'fhirType' => 'Reference',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Reference',
				'jsonKey' => 'valueReference',
			],
			[
				'fhirType' => 'SampledData',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\SampledData',
				'jsonKey' => 'valueSampledData',
			],
			[
				'fhirType' => 'Signature',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Signature',
				'jsonKey' => 'valueSignature',
			],
			[
				'fhirType' => 'Timing',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Timing',
				'jsonKey' => 'valueTiming',
			],
			[
				'fhirType' => 'ContactDetail',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\ContactDetail',
				'jsonKey' => 'valueContactDetail',
			],
			[
				'fhirType' => 'DataRequirement',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\DataRequirement',
				'jsonKey' => 'valueDataRequirement',
			],
			[
				'fhirType' => 'Expression',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Expression',
				'jsonKey' => 'valueExpression',
			],
			[
				'fhirType' => 'ParameterDefinition',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\ParameterDefinition',
				'jsonKey' => 'valueParameterDefinition',
			],
			[
				'fhirType' => 'RelatedArtifact',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\RelatedArtifact',
				'jsonKey' => 'valueRelatedArtifact',
			],
			[
				'fhirType' => 'TriggerDefinition',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\TriggerDefinition',
				'jsonKey' => 'valueTriggerDefinition',
			],
			[
				'fhirType' => 'UsageContext',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\UsageContext',
				'jsonKey' => 'valueUsageContext',
			],
			[
				'fhirType' => 'Availability',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Availability',
				'jsonKey' => 'valueAvailability',
			],
			[
				'fhirType' => 'ExtendedContactDetail',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\ExtendedContactDetail',
				'jsonKey' => 'valueExtendedContactDetail',
			],
			[
				'fhirType' => 'Dosage',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Dosage',
				'jsonKey' => 'valueDosage',
			],
			[
				'fhirType' => 'Meta',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R5\DataType\Meta',
				'jsonKey' => 'valueMeta',
			],
		],
		)]
		#[\Symfony\Component\Validator\Constraints\NotBlank]
		public \Ardenexal\FHIRTools\Component\Models\R5\Primitive\Base64BinaryPrimitive|bool|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\CanonicalPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\CodePrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\DatePrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\DateTimePrimitive|float|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\IdPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\InstantPrimitive|int|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\Integer64Primitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\MarkdownPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\OidPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\PositiveIntPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\StringPrimitive|string|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\TimePrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\UnsignedIntPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\UriPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\UrlPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\Primitive\UuidPrimitive|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Address|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Age|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Annotation|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Attachment|\Ardenexal\FHIRTools\Component\Models\R5\DataType\CodeableConcept|\Ardenexal\FHIRTools\Component\Models\R5\DataType\CodeableReference|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Coding|\Ardenexal\FHIRTools\Component\Models\R5\DataType\ContactPoint|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Count|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Distance|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Duration|\Ardenexal\FHIRTools\Component\Models\R5\DataType\HumanName|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Identifier|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Money|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Period|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Quantity|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Range|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Ratio|\Ardenexal\FHIRTools\Component\Models\R5\DataType\RatioRange|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Reference|\Ardenexal\FHIRTools\Component\Models\R5\DataType\SampledData|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Signature|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Timing|\Ardenexal\FHIRTools\Component\Models\R5\DataType\ContactDetail|\Ardenexal\FHIRTools\Component\Models\R5\DataType\DataRequirement|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Expression|\Ardenexal\FHIRTools\Component\Models\R5\DataType\ParameterDefinition|\Ardenexal\FHIRTools\Component\Models\R5\DataType\RelatedArtifact|\Ardenexal\FHIRTools\Component\Models\R5\DataType\TriggerDefinition|\Ardenexal\FHIRTools\Component\Models\R5\DataType\UsageContext|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Availability|\Ardenexal\FHIRTools\Component\Models\R5\DataType\ExtendedContactDetail|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Dosage|\Ardenexal\FHIRTools\Component\Models\R5\DataType\Meta|null $value = null,
	) {
		parent::__construct($id, $extension, $modifierExtension);
	}
}
