name: Bug Report
description: Report a bug or unexpected behaviour
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CodeGeneration
        - Serialization
        - Models (generated)
        - FHIRPath
        - FHIRBundle (Symfony)
        - Other / Unsure
    validations:
      required: true

  - type: dropdown
    id: fhir-version
    attributes:
      label: FHIR Version
      description: Which FHIR version are you working with?
      options:
        - R4
        - R4B
        - R5
        - Not applicable
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behaviour.
      placeholder: |
        1. Run command '...'
        2. Pass this input '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: What actually happened? Include error messages or stack traces if applicable.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide your environment details.
      value: |
        - PHP version:
        - Symfony version:
        - Package version:
        - OS:
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or log output that might help.
    validations:
      required: false
