<?php declare(strict_types=1);

namespace Ardenexal\FHIRTools\Component\Models\R4B\Resource\StructureMap;

/**
 * @description Source inputs to the mapping.
 */
#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FHIRBackboneElement(parentResource: 'StructureMap', elementPath: 'StructureMap.group.rule.source', fhirVersion: 'R4B')]
class StructureMapGroupRuleSource extends \Ardenexal\FHIRTools\Component\Models\R4B\DataType\BackboneElement
{
	public const FHIR_PROPERTY_MAP = [
		'id' => [
			'fhirType' => 'http://hl7.org/fhirpath/System.String',
			'propertyKind' => 'scalar',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'extension' => [
			'fhirType' => 'Extension',
			'propertyKind' => 'extension',
			'isArray' => true,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'modifierExtension' => [
			'fhirType' => 'Extension',
			'propertyKind' => 'modifierExtension',
			'isArray' => true,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'context' => [
			'fhirType' => 'id',
			'propertyKind' => 'primitive',
			'isArray' => false,
			'isRequired' => true,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'min' => [
			'fhirType' => 'integer',
			'propertyKind' => 'scalar',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'max' => [
			'fhirType' => 'string',
			'propertyKind' => 'primitive',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'type' => [
			'fhirType' => 'string',
			'propertyKind' => 'primitive',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'defaultValueX' => [
			'fhirType' => 'choice',
			'propertyKind' => 'choice',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => true,
			'jsonKey' => null,
			'variants' => [
				[
					'fhirType' => 'base64Binary',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\Base64BinaryPrimitive',
					'jsonKey' => 'defaultValueBase64Binary',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'boolean',
					'propertyKind' => 'scalar',
					'phpType' => 'bool',
					'jsonKey' => 'defaultValueBoolean',
					'isBuiltin' => true,
				],
				[
					'fhirType' => 'canonical',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CanonicalPrimitive',
					'jsonKey' => 'defaultValueCanonical',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'code',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CodePrimitive',
					'jsonKey' => 'defaultValueCode',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'date',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DatePrimitive',
					'jsonKey' => 'defaultValueDate',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'dateTime',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DateTimePrimitive',
					'jsonKey' => 'defaultValueDateTime',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'decimal',
					'propertyKind' => 'scalar',
					'phpType' => 'float',
					'jsonKey' => 'defaultValueDecimal',
					'isBuiltin' => true,
				],
				[
					'fhirType' => 'id',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\IdPrimitive',
					'jsonKey' => 'defaultValueId',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'instant',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\InstantPrimitive',
					'jsonKey' => 'defaultValueInstant',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'integer',
					'propertyKind' => 'scalar',
					'phpType' => 'int',
					'jsonKey' => 'defaultValueInteger',
					'isBuiltin' => true,
				],
				[
					'fhirType' => 'markdown',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\MarkdownPrimitive',
					'jsonKey' => 'defaultValueMarkdown',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'oid',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\OidPrimitive',
					'jsonKey' => 'defaultValueOid',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'positiveInt',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\PositiveIntPrimitive',
					'jsonKey' => 'defaultValuePositiveInt',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'string',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive',
					'jsonKey' => 'defaultValueString',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'time',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\TimePrimitive',
					'jsonKey' => 'defaultValueTime',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'unsignedInt',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UnsignedIntPrimitive',
					'jsonKey' => 'defaultValueUnsignedInt',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'uri',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UriPrimitive',
					'jsonKey' => 'defaultValueUri',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'url',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UrlPrimitive',
					'jsonKey' => 'defaultValueUrl',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'uuid',
					'propertyKind' => 'primitive',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UuidPrimitive',
					'jsonKey' => 'defaultValueUuid',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Address',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Address',
					'jsonKey' => 'defaultValueAddress',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Age',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Age',
					'jsonKey' => 'defaultValueAge',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Annotation',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Annotation',
					'jsonKey' => 'defaultValueAnnotation',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Attachment',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Attachment',
					'jsonKey' => 'defaultValueAttachment',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'CodeableConcept',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\CodeableConcept',
					'jsonKey' => 'defaultValueCodeableConcept',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Coding',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Coding',
					'jsonKey' => 'defaultValueCoding',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'ContactPoint',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactPoint',
					'jsonKey' => 'defaultValueContactPoint',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Count',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Count',
					'jsonKey' => 'defaultValueCount',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Distance',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Distance',
					'jsonKey' => 'defaultValueDistance',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Duration',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Duration',
					'jsonKey' => 'defaultValueDuration',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'HumanName',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\HumanName',
					'jsonKey' => 'defaultValueHumanName',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Identifier',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Identifier',
					'jsonKey' => 'defaultValueIdentifier',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Money',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Money',
					'jsonKey' => 'defaultValueMoney',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Period',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Period',
					'jsonKey' => 'defaultValuePeriod',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Quantity',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Quantity',
					'jsonKey' => 'defaultValueQuantity',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Range',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Range',
					'jsonKey' => 'defaultValueRange',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Ratio',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Ratio',
					'jsonKey' => 'defaultValueRatio',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Reference',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Reference',
					'jsonKey' => 'defaultValueReference',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'SampledData',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\SampledData',
					'jsonKey' => 'defaultValueSampledData',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Signature',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Signature',
					'jsonKey' => 'defaultValueSignature',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Timing',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Timing',
					'jsonKey' => 'defaultValueTiming',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'ContactDetail',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactDetail',
					'jsonKey' => 'defaultValueContactDetail',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Contributor',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Contributor',
					'jsonKey' => 'defaultValueContributor',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'DataRequirement',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\DataRequirement',
					'jsonKey' => 'defaultValueDataRequirement',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Expression',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Expression',
					'jsonKey' => 'defaultValueExpression',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'ParameterDefinition',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\ParameterDefinition',
					'jsonKey' => 'defaultValueParameterDefinition',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'RelatedArtifact',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\RelatedArtifact',
					'jsonKey' => 'defaultValueRelatedArtifact',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'TriggerDefinition',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\TriggerDefinition',
					'jsonKey' => 'defaultValueTriggerDefinition',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'UsageContext',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\UsageContext',
					'jsonKey' => 'defaultValueUsageContext',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Dosage',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Dosage',
					'jsonKey' => 'defaultValueDosage',
					'isBuiltin' => false,
				],
				[
					'fhirType' => 'Meta',
					'propertyKind' => 'complex',
					'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Meta',
					'jsonKey' => 'defaultValueMeta',
					'isBuiltin' => false,
				],
			],
		],
		'element' => [
			'fhirType' => 'string',
			'propertyKind' => 'primitive',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'listMode' => [
			'fhirType' => 'code',
			'propertyKind' => 'primitive',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'variable' => [
			'fhirType' => 'id',
			'propertyKind' => 'primitive',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'condition' => [
			'fhirType' => 'string',
			'propertyKind' => 'primitive',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'check' => [
			'fhirType' => 'string',
			'propertyKind' => 'primitive',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
		'logMessage' => [
			'fhirType' => 'string',
			'propertyKind' => 'primitive',
			'isArray' => false,
			'isRequired' => false,
			'isChoice' => false,
			'jsonKey' => null,
			'variants' => null,
		],
	];

	public function __construct(
		/** @var null|string id Unique id for inter-element referencing */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'http://hl7.org/fhirpath/System.String', propertyKind: 'scalar')]
		public ?string $id = null,
		/** @var  array<\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Extension> extension Additional content defined by implementations */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'Extension', propertyKind: 'extension', isArray: true)]
		public array $extension = [],
		/** @var  array<\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Extension> modifierExtension Extensions that cannot be ignored even if unrecognized */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'Extension', propertyKind: 'modifierExtension', isArray: true)]
		public array $modifierExtension = [],
		/** @var null|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\IdPrimitive context Type or variable this rule applies to */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'id', propertyKind: 'primitive', isRequired: true), \Symfony\Component\Validator\Constraints\NotBlank]
		public ?\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\IdPrimitive $context = null,
		/** @var null|int min Specified minimum cardinality */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'integer', propertyKind: 'scalar')]
		public ?int $min = null,
		/** @var null|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string max Specified maximum cardinality (number or *) */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'string', propertyKind: 'primitive')]
		public \Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string|null $max = null,
		/** @var null|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string type Rule only applies if source has this type */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'string', propertyKind: 'primitive')]
		public \Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string|null $type = null,
		/** @var null|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\Base64BinaryPrimitive|bool|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CanonicalPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CodePrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DatePrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DateTimePrimitive|float|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\IdPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\InstantPrimitive|int|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\MarkdownPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\OidPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\PositiveIntPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\TimePrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UnsignedIntPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UriPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UrlPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UuidPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Address|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Age|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Annotation|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Attachment|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\CodeableConcept|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Coding|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactPoint|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Count|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Distance|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Duration|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\HumanName|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Identifier|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Money|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Period|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Quantity|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Range|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Ratio|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Reference|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\SampledData|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Signature|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Timing|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactDetail|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Contributor|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\DataRequirement|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Expression|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\ParameterDefinition|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\RelatedArtifact|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\TriggerDefinition|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\UsageContext|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Dosage|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Meta defaultValueX Default value if no value exists */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(
			fhirType: 'choice',
			propertyKind: 'choice',
			isChoice: true,
			variants: [
			[
				'fhirType' => 'base64Binary',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\Base64BinaryPrimitive',
				'jsonKey' => 'defaultValueBase64Binary',
			],
			['fhirType' => 'boolean', 'propertyKind' => 'scalar', 'phpType' => 'bool', 'jsonKey' => 'defaultValueBoolean'],
			[
				'fhirType' => 'canonical',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CanonicalPrimitive',
				'jsonKey' => 'defaultValueCanonical',
			],
			[
				'fhirType' => 'code',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CodePrimitive',
				'jsonKey' => 'defaultValueCode',
			],
			[
				'fhirType' => 'date',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DatePrimitive',
				'jsonKey' => 'defaultValueDate',
			],
			[
				'fhirType' => 'dateTime',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DateTimePrimitive',
				'jsonKey' => 'defaultValueDateTime',
			],
			['fhirType' => 'decimal', 'propertyKind' => 'scalar', 'phpType' => 'float', 'jsonKey' => 'defaultValueDecimal'],
			[
				'fhirType' => 'id',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\IdPrimitive',
				'jsonKey' => 'defaultValueId',
			],
			[
				'fhirType' => 'instant',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\InstantPrimitive',
				'jsonKey' => 'defaultValueInstant',
			],
			['fhirType' => 'integer', 'propertyKind' => 'scalar', 'phpType' => 'int', 'jsonKey' => 'defaultValueInteger'],
			[
				'fhirType' => 'markdown',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\MarkdownPrimitive',
				'jsonKey' => 'defaultValueMarkdown',
			],
			[
				'fhirType' => 'oid',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\OidPrimitive',
				'jsonKey' => 'defaultValueOid',
			],
			[
				'fhirType' => 'positiveInt',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\PositiveIntPrimitive',
				'jsonKey' => 'defaultValuePositiveInt',
			],
			[
				'fhirType' => 'string',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive',
				'jsonKey' => 'defaultValueString',
			],
			[
				'fhirType' => 'time',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\TimePrimitive',
				'jsonKey' => 'defaultValueTime',
			],
			[
				'fhirType' => 'unsignedInt',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UnsignedIntPrimitive',
				'jsonKey' => 'defaultValueUnsignedInt',
			],
			[
				'fhirType' => 'uri',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UriPrimitive',
				'jsonKey' => 'defaultValueUri',
			],
			[
				'fhirType' => 'url',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UrlPrimitive',
				'jsonKey' => 'defaultValueUrl',
			],
			[
				'fhirType' => 'uuid',
				'propertyKind' => 'primitive',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UuidPrimitive',
				'jsonKey' => 'defaultValueUuid',
			],
			[
				'fhirType' => 'Address',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Address',
				'jsonKey' => 'defaultValueAddress',
			],
			[
				'fhirType' => 'Age',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Age',
				'jsonKey' => 'defaultValueAge',
			],
			[
				'fhirType' => 'Annotation',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Annotation',
				'jsonKey' => 'defaultValueAnnotation',
			],
			[
				'fhirType' => 'Attachment',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Attachment',
				'jsonKey' => 'defaultValueAttachment',
			],
			[
				'fhirType' => 'CodeableConcept',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\CodeableConcept',
				'jsonKey' => 'defaultValueCodeableConcept',
			],
			[
				'fhirType' => 'Coding',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Coding',
				'jsonKey' => 'defaultValueCoding',
			],
			[
				'fhirType' => 'ContactPoint',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactPoint',
				'jsonKey' => 'defaultValueContactPoint',
			],
			[
				'fhirType' => 'Count',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Count',
				'jsonKey' => 'defaultValueCount',
			],
			[
				'fhirType' => 'Distance',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Distance',
				'jsonKey' => 'defaultValueDistance',
			],
			[
				'fhirType' => 'Duration',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Duration',
				'jsonKey' => 'defaultValueDuration',
			],
			[
				'fhirType' => 'HumanName',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\HumanName',
				'jsonKey' => 'defaultValueHumanName',
			],
			[
				'fhirType' => 'Identifier',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Identifier',
				'jsonKey' => 'defaultValueIdentifier',
			],
			[
				'fhirType' => 'Money',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Money',
				'jsonKey' => 'defaultValueMoney',
			],
			[
				'fhirType' => 'Period',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Period',
				'jsonKey' => 'defaultValuePeriod',
			],
			[
				'fhirType' => 'Quantity',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Quantity',
				'jsonKey' => 'defaultValueQuantity',
			],
			[
				'fhirType' => 'Range',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Range',
				'jsonKey' => 'defaultValueRange',
			],
			[
				'fhirType' => 'Ratio',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Ratio',
				'jsonKey' => 'defaultValueRatio',
			],
			[
				'fhirType' => 'Reference',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Reference',
				'jsonKey' => 'defaultValueReference',
			],
			[
				'fhirType' => 'SampledData',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\SampledData',
				'jsonKey' => 'defaultValueSampledData',
			],
			[
				'fhirType' => 'Signature',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Signature',
				'jsonKey' => 'defaultValueSignature',
			],
			[
				'fhirType' => 'Timing',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Timing',
				'jsonKey' => 'defaultValueTiming',
			],
			[
				'fhirType' => 'ContactDetail',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactDetail',
				'jsonKey' => 'defaultValueContactDetail',
			],
			[
				'fhirType' => 'Contributor',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Contributor',
				'jsonKey' => 'defaultValueContributor',
			],
			[
				'fhirType' => 'DataRequirement',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\DataRequirement',
				'jsonKey' => 'defaultValueDataRequirement',
			],
			[
				'fhirType' => 'Expression',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Expression',
				'jsonKey' => 'defaultValueExpression',
			],
			[
				'fhirType' => 'ParameterDefinition',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\ParameterDefinition',
				'jsonKey' => 'defaultValueParameterDefinition',
			],
			[
				'fhirType' => 'RelatedArtifact',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\RelatedArtifact',
				'jsonKey' => 'defaultValueRelatedArtifact',
			],
			[
				'fhirType' => 'TriggerDefinition',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\TriggerDefinition',
				'jsonKey' => 'defaultValueTriggerDefinition',
			],
			[
				'fhirType' => 'UsageContext',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\UsageContext',
				'jsonKey' => 'defaultValueUsageContext',
			],
			[
				'fhirType' => 'Dosage',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Dosage',
				'jsonKey' => 'defaultValueDosage',
			],
			[
				'fhirType' => 'Meta',
				'propertyKind' => 'complex',
				'phpType' => 'Ardenexal\FHIRTools\Component\Models\R4B\DataType\Meta',
				'jsonKey' => 'defaultValueMeta',
			],
		],
		)]
		public \Ardenexal\FHIRTools\Component\Models\R4B\Primitive\Base64BinaryPrimitive|bool|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CanonicalPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\CodePrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DatePrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\DateTimePrimitive|float|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\IdPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\InstantPrimitive|int|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\MarkdownPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\OidPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\PositiveIntPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\TimePrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UnsignedIntPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UriPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UrlPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\UuidPrimitive|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Address|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Age|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Annotation|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Attachment|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\CodeableConcept|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Coding|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactPoint|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Count|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Distance|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Duration|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\HumanName|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Identifier|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Money|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Period|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Quantity|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Range|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Ratio|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Reference|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\SampledData|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Signature|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Timing|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\ContactDetail|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Contributor|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\DataRequirement|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Expression|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\ParameterDefinition|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\RelatedArtifact|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\TriggerDefinition|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\UsageContext|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Dosage|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\Meta|null $defaultValueX = null,
		/** @var null|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string element Optional field for this source */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'string', propertyKind: 'primitive')]
		public \Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string|null $element = null,
		/** @var null|\Ardenexal\FHIRTools\Component\Models\R4B\DataType\StructureMapSourceListModeType listMode first | not_first | last | not_last | only_one */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'code', propertyKind: 'primitive')]
		public ?\Ardenexal\FHIRTools\Component\Models\R4B\DataType\StructureMapSourceListModeType $listMode = null,
		/** @var null|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\IdPrimitive variable Named context for field, if a field is specified */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'id', propertyKind: 'primitive')]
		public ?\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\IdPrimitive $variable = null,
		/** @var null|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string condition FHIRPath expression  - must be true or the rule does not apply */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'string', propertyKind: 'primitive')]
		public \Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string|null $condition = null,
		/** @var null|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string check FHIRPath expression  - must be true or the mapping engine throws an error instead of completing */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'string', propertyKind: 'primitive')]
		public \Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string|null $check = null,
		/** @var null|\Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string logMessage Message to put in log if source exists (FHIRPath) */
		#[\Ardenexal\FHIRTools\Component\CodeGeneration\Attributes\FhirProperty(fhirType: 'string', propertyKind: 'primitive')]
		public \Ardenexal\FHIRTools\Component\Models\R4B\Primitive\StringPrimitive|string|null $logMessage = null,
	) {
		parent::__construct($id, $extension, $modifierExtension);
	}
}
